// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"goauth/app/user/v1/internal/biz"
	"goauth/app/user/v1/internal/conf"
	"goauth/app/user/v1/internal/data"
	"goauth/app/user/v1/internal/server"
	"goauth/app/user/v1/internal/service"
	"goauth/app/user/v1/middleware/registry"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confRegistry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(userRepo, logger)
	userService := service.NewUserService(userUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	registrar := registry.NewConsulRegistry(confRegistry)
	app := newApp(logger, grpcServer, registrar, confServer)
	return app, func() {
		cleanup()
	}, nil
}
