server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
    name: user.rpc
    version: V1.0.0
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/user?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  address: 127.0.0.1:8500